src/Entity/Movie.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MovieRepository")
 */
class Movie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cover;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $actores;

    /**
     * @ORM\Column(type="decimal", precision=5, scale=2)
     */
    private $price;
    
    /**
     * @var integer
     * 
     * @ORM\Column(name="nb_orders", type="integer")
     */
    private $nbOrders = 0;
    
    /**
     * @var integer
     *
     * @ORM\Column(name="nb_reviews", type="integer")
     */
    private $nbReviews = 0;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;
    
    /**
     * @var ArrayCollection
     *
     * * @ORM\OneToMany(targetEntity="Review", mappedBy="movie")
     */
    protected $reviews;

    /**
     * @var ArrayCollection
     * 
     * @ORM\ManyToMany(targetEntity="Category", inversedBy="movies")
     */
    protected $categories;
    
    /**
     * @var ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="Order", mappedBy="movies")
     */
    protected $orders;
    
    public function __construct()
    {
        $this->createdAt = new \DateTime;
    }
    
    public function __toString()
    {
        return $this->getName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCover(): ?string
    {
        return $this->cover;
    }

    public function setCover(string $cover): self
    {
        $this->cover = $cover;

        return $this;
    }

    public function getActores(): ?string
    {
        return $this->actores;
    }

    public function setActores(?string $actores): self
    {
        $this->actores = $actores;

        return $this;
    }

    public function getPrice()
    {
        return $this->price;
    }

    public function setPrice($price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
    
    /**
     * Add reviews
     *
     * @param \App\Entity\Review $reviews
     * @return Movie
     */
    public function addReview(\App\Entity\Review $reviews)
    {
        $this->reviews[] = $reviews;

        return $this;
    }

    /**
     * Remove reviews
     *
     * @param \App\Entity\Review $reviews
     */
    public function removeReview(\App\Entity\Review $reviews)
    {
        $this->reviews->removeElement($reviews);
    }

    /**
     * Get reviews
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getReviews()
    {
        return $this->reviews;
    }
    
    public function getApprovedReviews()
    {
        $reviews = array();
        foreach ($this->getReviews() as $review) {
            if ($review->getIsModerated()) {
                $reviews[] = $review;
            }
        }
        
        return $reviews;
    }
    
    /**
     * Add categories
     *
     * @param \App\Entity\Category $categories
     * @return Movie
     */
    public function addCategory(\App\Entity\Category $categories)
    {
        $this->categories[] = $categories;

        return $this;
    }

    /**
     * Remove categories
     *
     * @param \App\Entity\Category $categories
     */
    public function removeCategory(\App\Entity\Category $categories)
    {
        $this->categories->removeElement($categories);
    }

    /**
     * Get categories
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getCategories()
    {
        return $this->categories;
    }

    /**
     * Add orders
     *
     * @param \App\Entity\Order $orders
     * @return Movie
     */
    public function addOrder(\App\Entity\Order $orders)
    {
        $this->orders[] = $orders;

        return $this;
    }

    /**
     * Remove orders
     *
     * @param \App\Entity\Order $orders
     */
    public function removeOrder(\App\Entity\Order $orders)
    {
        $this->orders->removeElement($orders);
    }

    /**
     * Get orders
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getOrders()
    {
        return $this->orders;
    }
    
    /**
     * Set nbOrders
     *
     * @param integer $nbOrders
     * @return Movie
     */
    public function setNbOrders($nbOrders)
    {
        $this->nbOrders = $nbOrders;

        return $this;
    }

    /**
     * Get nbOrders
     *
     * @return integer 
     */
    public function getNbOrders()
    {
        return $this->nbOrders;
    }

    /**
     * Set nbReviews
     *
     * @param integer $nbReviews
     * @return Movie
     */
    public function setNbReviews($nbReviews)
    {
        $this->nbReviews = $nbReviews;

        return $this;
    }

    /**
     * Get nbReviews
     *
     * @return integer 
     */
    public function getNbReviews()
    {
        return $this->nbReviews;
    }
}

src/Controller/MovieController.php
<?php
namespace App\Controller;

use App\Entity\Movie;
use App\Entity\Order;
use App\Service\Cart;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/movie")
 */
class MovieController extends AbstractController
{
    
    /**
     * @IsGranted("ROLE_USER")
     *
     * @Route("/order", name="movie_order")
     */
    public function orderAction(Cart $cart, \Swift_Mailer $mailer)
    {
        $movies = $cart->getMovies();
        if (count($movies) < 1) {
            // film jest już w koszyku
            $this->addFlash('error', "Nie możesz złożyć zamówienia - koszyk jest pusty.");
        }
    
        $user = $this->getUser();
    
        $order = new Order();
        $order->setUser($user);
        foreach ($movies as $movie) {
            $order->addMovie($movie);
            
            // aktualizuj liczbę zamówień dla filmu
            $movie->setNbOrders($movie->getNbOrders() + 1);
        }
    
        $em = $this->getDoctrine()->getManager();
    
        $em->persist($order);
        $em->flush();
    
        // wyczyść koszyk
        $cart->clear();
    
        // wyślij miala ze szczegółami płatności
        $message = $mailer->createMessage()
            ->setSubject('MovieShop.pl - potwierdzenie zamówienia')
            ->setFrom('no-reply@movieshop.pl')
            ->setTo($user->getEmail())
            ->setBody($this->renderView(
                'movie/emailConfirmation.html.twig',
                array('user' => $user)
        ),'text/html');
        
        $mailer->send($message);
        
        $this->addFlash('notice', "Zamówienie zostało zapisane. Na podany adres e-mail zostały wysłane informacje na temat płatności.");
    
        return $this->redirectToRoute('order_confirm', array('id' => $order->getId()));
    }
    
    /**
     * @Route("/{id}", name="movie_show")
     */
    public function showAction($id)
    {
        $movie = $this->getDoctrine()->getRepository(Movie::class)
            ->find($id);
        
        if (!$movie) {
            throw $this->createNotFoundException("Film nie został odnaleziony.");
        }
        
        return $this->render('movie/show.html.twig', [
            'movie' => $movie
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * 
     * @Route("/{id}/rent", name="movie_rent")
     */
    public function rentAction($id, Request $request, Cart $cart)
    {
        $movie = $this->getDoctrine()->getRepository(Movie::class)
            ->find($id);
        
        if (!$movie) {
            throw $this->createNotFoundException("Film nie został odnaleziony.");
        }
        
        if ($cart->has($movie)) {
            // film jest już w koszyku
            $this->addFlash('error', "Ten film znajduje się już w Twoim koszyku.");
        } else {
            $cart->add($movie);
            $this->addFlash('notice', "Film został pomyślnie dodany do koszyka.");
        }
        
        return $this->redirect($request->headers->get('referer'));
    }
    
    /**
     * @Route("/{id}/watch", name="movie_watch")
     */
    public function watchAction($id, Request $request)
    {
        $movie = $this->getDoctrine()->getRepository(Movie::class)
            ->find($id);

        if (!$movie) {
            throw $this->createNotFoundException("Film nie został odnaleziony.");
        }
        
        if (!$this->getUser()->isOrderedMovie($movie)) {
            $this->addFlash('error', 'Ten film nie został jeszcze opłacony!');
            return $this->redirectToRoute('homepage');
        }
        
        $this->addFlash('notice', "Odtwarzanie filmu");
    
        return $this->redirect($request->headers->get('referer'));
    }
    
    /**
     * @IsGranted("ROLE_USER")
     * 
     * @Route("/{id}/add-review", name="movie_add_review")
     */
    public function addReviewAction($id, Request $request)
    {
        $movie = $this->getDoctrine()->getRepository(Movie::class)
            ->find($id);
        
        if (!$movie) {
            throw $this->createNotFoundException("Film nie został odnaleziony.");
        }
        
        $review = new \App\Entity\Review();
        $review->setMovie($movie);
        $review->setUser($this->getUser());
        
        $form = $this->createForm(\App\Form\ReviewType::class, $review);
        
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            
            $em = $this->getDoctrine()->getManager();
            $em->persist($review);
            
            // zwiększa liczbę opinie
            $movie->setNbReviews($movie->getNbReviews() + 1);
            
            $em->flush();
            
            $this->addFlash('notice', "Recenzja została pomyślnie dodana i oczekuje na moderację.");
            return $this->redirectToRoute('movie_show', array('id' => $movie->getId()));
        }
        
        return $this->render('movie/addReview.html.twig', [
            'movie' => $movie,
            'form'  => $form->createView()
        ]);
    }
}

templates/movie/addReview.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ movie.name }} - dodaj recenzję{% endblock %}

{% block body %}


  <div class="page-header">
    <h1>{{ block('title') }}</h1>
  </div>
  
  <div>
    
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
    
  </div>

{% endblock %}

templates/movie/emailConfirmation.html.twig
Witaj, {{ user }}

Wiadomość email z informacjami of formie, warunkach i terminie
płatności

Zespół,

MovieShop.pl

templates/movie/list.html.twig
<table class="table table-striped">
    <thead>
        <tr>
            <th>#</th>
            <th>Plakat</th>
            <th>Tytuł filmu</th>
            <th>Gatunek</th>
            <th>Cena wypożyczenia</th>
        </tr>
    </thead>
    <tbody>
        {% for movie in movies %}
            <tr>
                <td>{{ loop.index }}</td>
                <td><a href="{{ path('movie_show', {'id': movie.id}) }}" title="Zobacz więcej o: {{ movie.name }}"><img width=100 src="{{ asset('uploads/' ~ movie.cover) }}" /></a></td>
                <td><a href="{{ path('movie_show', {'id': movie.id}) }}" title="Zobacz więcej o: {{ movie.name }}">{{ movie.name }}</a></td>
                <td>{{ movie.categories|join(", ") }}</td>
                <td>{{ movie.price|number_format }} zł</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

templates/movie/rent.html.twig
{% extends "base.html.twig" %}

{% block title %}AppBundle:Movie:rent{% endblock %}

{% block body %}
<h1>Welcome to the Movie:rent page</h1>
{% endblock %}

templates/movie/show.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ movie.name }}{% endblock %}

{% block body %}

<h1>{{ block('title') }}</h1>
  
<div class="row">
    
    <img class="pull-right" width=200 src="{{ asset('uploads/' ~ movie.cover) }}" />
    
    {% for category in movie.categories %}
        <a class="label label-info" href="{{ path('category_show', {'id': category.id}) }}">{{ category.name }}</a>
    {% endfor %}
  
    <h3>Cena <span class="label label-default">{{ movie.price }} zł</span></h3>
  
    <h3>Opis</h3>
    <p>{{ movie.description }}</p>
  
  
    <h3>Obsada</h3>
    <p>{{ movie.actores|raw }}</p>
  
    <a href="{{ path('movie_rent', {'id': movie.id}) }}" class="btn btn-info">Wypożycz</a>
  
    <h3>Recenzje {% if app.user %}<a href="{{ path('movie_add_review', {'id': movie.id}) }}" class=" pull-right btn btn-success">Dodaj recenzje</a>{% endif %}</h3>
    {% if not app.user %}
        <p><a href="{{ path('fos_user_security_login') }}">Zaloguj się</a> by móc dodawać recenzje.</p>
    {% endif %}
    
    <ul class="list-group">
    {% for revision in movie.approvedReviews %}
        
        <li class="list-group-item ">
            <span class="pull-right">Dodana dnia: {{ revision.createdAt|date('Y-m-d H:i:s') }}</span>
            <h4 class="list-group-item-heading">{{ revision.user }}</h4>
            <p class="list-group-item-text">{{ revision.content }}</p>
        </li>
        
    {% else %}
    
        <li class="list-group-item ">Ten film nie posiada jeszcze żadnych recenzji</li>
      
    {% endfor %}
    </ul>
    
</div>
  
{% endblock %}